### ISSUE TITLE
Error when trying to create and edit a rack

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#192]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view    return func(*args, **kwargs)
  File "/limbus/app/storage/routes/rack.py", line 1147, in edit_rack    shelf_dict[int(shelf["site_id"])].append(KeyError: 3
```

**Comment by anthonyhorlock** [comment]
It did create the racks though

![image](https://user-images.githubusercontent.com/98022410/157894706-08d51675-3a46-41b1-9527-030d839ad504.png)

**Comment by anthonyhorlock** [comment]
I think this issue is similar to what has previously occurred. My admin profile only has the Biobank working site, and there aren't options to add the other sites onto this.

**Comment by KeironO** [comment]
https://github.com/AberystwythSystemsBiology/limbus/blob/dev/services/web/app/storage/routes/rack.py#L1146-L1150

Not seen this code before, but I think it only matters when instantiating a form? Might just write a error handler to check if it's a submitted form query or not, seeing as it doesn't break the actual outcome.
