### ISSUE TITLE
Error when clicking on a cell to enter a sample

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#224]
I have just been fed back an issue that has popped up when entering samples into a rack. 

When the user clicks on a cell to enter a sample, this Error 500 comes up (they can still assign samples, as per your update today):

```
Traceback (most recent call last):  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request    rv = self.dispatch_request() 

File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)

File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view    return func(*args, **kwargs)  File "/limbus/app/storage/routes/rack.py", line 648, in assign_rack_sample    

return render_template(  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 137, in render_template  

return _render(  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 120, in _render    rv = template.render(context)  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1090, in render    self.environment.handle_exception()  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 832, in handle_exception    reraise(*rewrite_traceback_stack(source=source))  File "/usr/local/lib/python3.8/dist-packages/jinja2/_compat.py", line 28, in reraise    raise value.with_traceback(tb)  File "/limbus/app/templates/storage/rack/sample_to_rack.html", line 1, in top-level template code    {% extends "template.html" %}  File "/limbus/app/templates/template.html", line 232, in top-level template code    {% block body %}  File "/limbus/app/templates/storage/rack/sample_to_rack.html", line 43, in block "body"    {{ form_field(form.fillopt_column_first) }}  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 679, in _invoke    rv = self._func(*arguments)  


File "/limbus/app/templates/macros.html", line 51, in template    &lt;div class="form-group {% if field.errors %}error{% endif %}" id="{{ field.id }}_div"&gt;  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 471, in getattr    

return getattr(obj, attribute)jinja2.exceptions.UndefinedError: 'app.storage.forms.StaticForm object' has no attribute 'fillopt_column_first
```

**Comment by pipaLU** [comment]
Already fixed, should reflect in next PR
