### ISSUE TITLE
Error message when attempting to log in

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#251]
A member of staff had an issue where they could not log in yesterday, but it strangely resolved itself after a couple of attempts to reload the page. 

I had a similar issue this morning, where the following message came up:

'''
Traceback (most recent call last):  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context    self.dialect.do_execute(  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 590, in do_execute    cursor.execute(statement, parameters)psycopg2.OperationalError: server closed the connection unexpectedly	This probably means the server terminated abnormally	before or while processing the request.The above exception was the direct cause of the following exception:Traceback (most recent call last):  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request    rv = self.dispatch_request()  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)  File "/limbus/app/auth/routes.py", line 39, in login    db.session.query(UserAccount)  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3300, in first    ret = list(self[0:1])  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3078, in __getitem__    return list(res)  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3405, in __iter__    return self._execute_and_instances(context)  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3430, in _execute_and_instances    result = conn.execute(querycontext.statement, self._params)  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 984, in execute    return meth(self, multiparams, params)  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection    return connection._execute_clauseelement(self, multiparams, params)  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1097, in _execute_clauseelement    ret = self._execute_context(  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1287, in _execute_context    self._handle_dbapi_exception(  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1481, in _handle_dbapi_exception    util.raise_(  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 178, in raise_    raise exception  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context    self.dialect.do_execute(  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 590, in do_execute    cursor.execute(statement, parameters)sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly	This probably means the server terminated abnormally	before or while processing the request.[SQL: SELECT useraccount.id AS useraccount_id, useraccount.is_locked AS useraccount_is_locked, useraccount.created_on AS useraccount_created_on, useraccount.updated_on AS useraccount_updated_on, useraccount.email AS useraccount_email, useraccount.password_hash AS useraccount_password_hash, useraccount.title AS useraccount_title, useraccount.first_name AS useraccount_first_name, useraccount.middle_name AS useraccount_middle_name, useraccount.last_name AS useraccount_last_name, useraccount.account_type AS useraccount_account_type, useraccount.access_control AS useraccount_access_control, useraccount.site_id AS useraccount_site_id, useraccount.settings AS useraccount_settings FROM useraccount WHERE lower(useraccount.email) = lower(%(lower_1)s) AND useraccount.is_locked = false  LIMIT %(param_1)s][parameters: {'lower_1': 'anthony.horlock@wales.nhs.uk', 'param_1': 1}](Background on this error at: http://sqlalche.me/e/e3q8)
'''

**Comment by pipaLU** [comment]
Sorted
