### ISSUE TITLE
Docker build issue

### ISSUE THREAD

**Issue by rob-a-bolton** [AberystwythSystemsBiology/LImBuS#42]
**Describe the bug**
Fails to build from Dockerfile

**To Reproduce**
Clone repo, source `helpers.sh`, run `limbus_setup_dev`

**Expected behavior**
`limbus_setup_dev` should correctly build.

**Screenshots**
```
Do you want to install yarn dependencies? (Y/N)
y
>>> Running yarn install:
Creating limbus_db_1 ... done
yarn install v1.22.10
warning package.json: No license field
warning limbus@0.0.1: No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.22s.
Do you want to set up the database? (Y/N)
Y
WARNING: THIS WILL DESTROY THE DATABASE, INCLUDING VERSIONS
Are you sure you want todo this? (Y/N)
Y
Starting limbus_db_1 ... done
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Starting limbus_db_1 ... done
rm: cannot remove 'migrations/versions/*': No such file or directory
Stopping limbus_db_1 ... done
Removing limbus_web_run_f0a987cdb96a ... done
Removing limbus_web_run_dcdb7e0015db ... done
Removing limbus_web_run_e056257b5ca0 ... done
Removing limbus_db_1                 ... done
Removing network limbus_default
Removing volume limbus_postgres_data
CREATING DATABASE
Creating network "limbus_default" with the default driver
Creating volume "limbus_postgres_data" with default driver
Creating limbus_db_1 ... done
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/alembic/config.py", line 577, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.6/dist-packages/alembic/config.py", line 571, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.6/dist-packages/alembic/config.py", line 551, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/local/lib/python3.6/dist-packages/alembic/command.py", line 214, in revision
    script_directory.run_env()
  File "/usr/local/lib/python3.6/dist-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.6/dist-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/dist-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 88, in <module>
    run_migrations_online()
  File "migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.6/dist-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.6/dist-packages/alembic/runtime/migration.py", line 509, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/local/lib/python3.6/dist-packages/alembic/command.py", line 190, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/usr/local/lib/python3.6/dist-packages/alembic/autogenerate/api.py", line 442, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/usr/local/lib/python3.6/dist-packages/alembic/autogenerate/api.py", line 482, in _run_environment
    autogen_context, migration_script
  File "/usr/local/lib/python3.6/dist-packages/alembic/autogenerate/compare.py", line 25, in _populate_migration_script
    _produce_net_changes(autogen_context, upgrade_ops)
  File "/usr/local/lib/python3.6/dist-packages/alembic/autogenerate/compare.py", line 51, in _produce_net_changes
    autogen_context, upgrade_ops, schemas
  File "/usr/local/lib/python3.6/dist-packages/alembic/util/langhelpers.py", line 303, in go
    fn(*arg, **kw)
  File "/usr/local/lib/python3.6/dist-packages/alembic/autogenerate/compare.py", line 75, in _autogen_for_tables
    [(table.schema, table.name) for table in autogen_context.sorted_tables]
  File "/usr/local/lib/python3.6/dist-packages/alembic/util/langhelpers.py", line 230, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python3.6/dist-packages/alembic/autogenerate/api.py", line 360, in sorted_tables
    result.extend(m.sorted_tables)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/schema.py", line 4120, in sorted_tables
    sorted(self.tables.values(), key=lambda t: t.key)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/ddl.py", line 1090, in sort_tables
    tables, filter_fn=_skip_fn, extra_dependencies=extra_dependencies
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/ddl.py", line 1159, in sort_tables_and_constraints
    dependent_on = fkc.referred_table
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/schema.py", line 3242, in referred_table
    return self.elements[0].column.table
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 883, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/schema.py", line 2049, in column
    tablekey,
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'coldstorage.room_id' could not find table 'rooms' with which to generate a foreign key to target column 'id'
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Creating Kryten
>>>> Creating Kryten
Starting limbus_db_1 ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "useraccount" does not exist
LINE 2: FROM useraccount
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/limbus/app/commands/setup.py", line 62, in create_kryten
    UserAccount.query.filter_by(email="kryten@jupiterminingcorp.co.uk").first()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3300, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3078, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3405, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3430, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "useraccount" does not exist
LINE 2: FROM useraccount
             ^

[SQL: SELECT useraccount.id AS useraccount_id, useraccount.is_locked AS useraccount_is_locked, useraccount.created_on AS useraccount_created_on, useraccount.updated_on AS useraccount_updated_on, useraccount.email AS useraccount_email, useraccount.password_hash AS useraccount_password_hash, useraccount.title AS useraccount_title, useraccount.first_name AS useraccount_first_name, useraccount.middle_name AS useraccount_middle_name, useraccount.last_name AS useraccount_last_name, useraccount.account_type AS useraccount_account_type, useraccount.access_control AS useraccount_access_control, useraccount.site_id AS useraccount_site_id
FROM useraccount
WHERE useraccount.email = %(email_1)s
 LIMIT %(param_1)s]
[parameters: {'email_1': 'kryten@jupiterminingcorp.co.uk', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/f405)
Creating dev user
You should now be able to start up your dev environment by running:
$ docker-compose up
Happy hacking :)
```

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser firefox
 - Version 32

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KeironO** [comment]
Fixed.

https://github.com/AberystwythSystemsBiology/limbus/commit/58309b404f3b6a3ab0cf7f9ba152da017d45a342

Thank you.
